version: '3.4'

services:
  scania.vehicle.monitoring.statusapi:
    volumes:
      - C:\Users\a.abdelahi\vsdbg\vs2017u5:/remote_debugger:ro
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_scania.vehicle.monitoring.statusapi$ Scania.Vehicle.Monitoring.StatusAPI.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
