version: '3.4'

services:
  scania.vehicle.monitoring.statusapi:
    image: scaniavehiclemonitoringstatusapi:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_scania.vehicle.monitoring.statusapi$
    volumes:
      - C:\Users\a.abdelahi\Source\Repos\Vehicle.Monitoring.API\Scania.Vehicle.Monitoring\src\Microservices\Scania.Vehicle.Monitoring.StatusAPI:/app
      - C:\Users\a.abdelahi\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_scania.vehicle.monitoring.statusapi$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_scania.vehicle.monitoring.statusapi$ bin/Debug/netcoreapp2.1/Scania.Vehicle.Monitoring.StatusAPI.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
